### ISSUE TITLE
[Feature Request] Arena Names, Inventory Saving, More Slots

### ISSUE THREAD

**Issue by KadTheHunter** [McMelonTV/SumoPMMP#2]
This is an amazing plugin that works well with no crashes or bugs found so far, but I have 2 feature requests:

1) Join Signs should show the arena name rather than world name. This would be useful for when you have multiple Sumo arenas in 1 world, each with a different build style and arena name.

2) Inventories should be saved upon entering the match and restored upon leaving it, so players don't lose items.

3) Allow more than just 2 players. It would be cool to have a 4 player sumo match.

Hope these things can be added soon :)

**Comment by McMelonTV** [comment]
Hey @KadTheHunter,

These feature requests are great but:

1. I may add this at some point but you can just use more worlds for now.
2. This is a planned feature but i dont currently have much time to make progress on this plugin
3. I think the whole point of the sumo minigame is that there are ***2*** players trying to knock each other to the void
