### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by callumrawlinson** [McMelonTV/SumoPMMP#4]
Hello Please can i adapt this to add blocks and items, if so how would i do this

**Comment by McMelonTV** [comment]
wdym

**Comment by callumrawlinson** [comment]
so i would like to make it so people could have items in sumo like potions and apple and stuff like that

**Comment by McMelonTV** [comment]
that breaks the whole point of sumo lol

**Comment by McMelonTV** [comment]
just download some 1v1 plugin from poggit

**Comment by callumrawlinson** [comment]
ok thank you for your time
